In [7]:
import gym
import numpy as np
import time
env = gym.make('FrozenLake-v0')

def choose_action(Q, s):
    epsilon = 0.3
    p = np. random. uniform( low=0, high=1)
    #print( p)
    if p > epsilon:
        return np. argmax( Q[s, : ] ) #say here, initial policy = for each state consider the action having highest Q- value
    else:
        return env. action_space. sample( )
    
#相关参数
lr = 0.8 #学习率
y = 0.95 #衰减因子
eps = 2000 #学习回合数
Q_table = np.zeros([env.observation_space.n,env.action_space.n])

for i in range(eps):
    s = env.reset()
    t = False
    j = 0
    while(j < 99):
        j+=1
        a = choose_action(Q_table, s)
        s_, r, t, _ = env.step(a)
        if r==0:
            if t==True:
                r = -5
                Q_table[s_] = np.ones(env.action_space.n)*r
            else:
                r = -1
        if r==1:
            r = 100
            Q_table[s_] = np.ones(env.action_space.n)*r
        Q_table[s,a] = Q_table[s,a] + lr * (r + y*np.max(Q_table[s_,:]) - Q_table[s,a])
        s = s_
        if t == True:
            break

print("Q-table")
print(Q_table)
print()

[2018-12-02 00:24:11,839] Making new env: FrozenLake-v0


Q-table
[[ 30.47393252  30.20922373  44.27348472  30.44304167]
 [ -7.28365695   8.73585071  38.57036563  83.29232374]
 [ 46.99906899  48.32813037  54.97466715  36.19133145]
 [ -9.48024044  39.45217583   0.69759648  41.93366695]
 [ 31.10307785  -7.98047238  30.44089689  29.21192906]
 [ -5.          -5.          -5.          -5.        ]
 [  9.86465341  -9.26593772  14.88397337  -9.49061442]
 [ -5.          -5.          -5.          -5.        ]
 [  2.14157358   1.65231459  -3.60497391 111.3737514 ]
 [ 12.14214101 118.03036109   6.08845749  -5.27941238]
 [ 99.5548347  127.88002247 122.5320909   58.74461158]
 [ -5.          -5.          -5.          -5.        ]
 [ -5.          -5.          -5.          -5.        ]
 [ 26.88027263  -6.76385917 101.91970359  -5.73597238]
 [135.91225268  59.27795926 183.39998528  68.27433626]
 [100.         100.         100.         100.        ]]



In [9]:
s = env.reset()
env.render()

while(True):
    print("=======")
    a = np.argmax(Q_table[s])
    print('s',s)
    print('a',a)
    s_,r,t,_ = env.step(a)
    env.render()
    s = s_
    if t==True:
        break


SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 4
a 0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 1
a 3
  (Up)
SFFF
FHFH
FFFH
HFFG
s 1
a 3
  (Up)
SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 4
a 0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 4
a 0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 1
a 3
  (Up)
SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 4
a 0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 4
a 0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 8
a 3
  (Up)
SFFF
FHFH
FFFH
HFFG
s 9
a 1
  (Down)
SFFF
FHFH
FFFH
HFFG
s 10
a 1
  (Down)
SFFF
FHFH
FFFH
HFFG
s 9
a 1
  (Down)
SFFF
FHFH
FFFH
HFFG
s 8
a 3
  (Up)
SFFF
FHFH
FFFH
HFFG
s 4
a 0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 4
a 0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 4
a 0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
a 2
  (Right