# Q-Table Learning

In [1]:
import gym
import numpy as np

### Load the environment

In [2]:
env = gym.make('FrozenLake-v0')

[2018-12-01 21:30:07,987] Making new env: FrozenLake-v0


### Implement Q-Table learning algorithm

In [15]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [16]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.4705


In [17]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[3.06019228e-01 8.93355828e-03 5.87352857e-03 4.58860955e-03]
 [2.03520352e-04 1.58343908e-03 2.04082238e-04 1.64172232e-01]
 [3.13738037e-03 1.67335759e-01 3.19026224e-03 3.29384341e-03]
 [1.57319617e-04 1.40472608e-04 5.14196246e-04 8.43696126e-02]
 [4.09278221e-01 7.25582253e-04 5.21958352e-04 4.88435594e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.90936066e-02 2.53345239e-04 3.50983230e-04 7.74931011e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.20036945e-03 1.12723430e-03 8.20343189e-04 4.21751362e-01]
 [1.35886929e-03 6.07948676e-01 1.16179187e-03 0.00000000e+00]
 [8.84559607e-01 1.04294437e-03 1.84270664e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.29962444e-04 5.89079277e-01 2.74852304e-04]
 [0.00000000e+00 0.00000000e+00 9.98965048e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.

In [19]:
s = env.reset()
env.render()

while(True):
    print("=======")
    a = np.argmax(Q[s])
    print(a)
    s_,r,t,_ = env.step(a)
    env.render()
    s = s_
    print('s',s)
    if t==True:
        break


SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 4
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 0
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 4
0
  (Left)
SFFF
FHFH
FFFH
HFFG
s 8
3
  (Up)
SFFF
FHFH
FFFH
HFFG
s 9
1
  (Down)
SFFF
FHFH
FFFH
HFFG
s 13
2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 14
2
  (Right)
SFFF
FHFH
FFFH
HFFG
s 15
